# Generated by Django 4.1.4 on 2022-12-15 17:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dbApp', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='r_details',
            name='id',
            field=models.Field(default=(-1, -1), primary_key=True, serialize=False, verbose_name=('reciept_id', 'item_id')),
        ),
    ]
