# Generated by Django 4.1.4 on 2022-12-17 21:44

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('dbApp', '0002_r_details_id'),
    ]

    operations = [
        migrations.CreateModel(
            name='Roles',
            fields=[
                ('role_number', models.AutoField(primary_key=True, serialize=False)),
                ('role_name', models.CharField(max_length=254)),
                ('roleid', models.IntegerField()),
            ],
        ),
        migrations.AlterField(
            model_name='card',
            name='user_id',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='dbApp.user'),
        ),
        migrations.AlterField(
            model_name='reserves',
            name='user_id',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='dbApp.user'),
        ),
        migrations.AlterField(
            model_name='servant',
            name='user_id',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, primary_key=True, serialize=False, to='dbApp.user'),
        ),
        migrations.DeleteModel(
            name='Donor',
        ),
        migrations.AddField(
            model_name='user',
            name='role',
            field=models.ForeignKey(default=-1, on_delete=django.db.models.deletion.CASCADE, to='dbApp.roles'),
        ),
    ]
