# Generated by Django 4.1.4 on 2022-12-19 13:19

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('dbApp', '0002_kero'),
    ]

    operations = [
        migrations.DeleteModel(
            name='kero',
        ),
    ]
