# Generated by Django 4.1.4 on 2022-12-19 17:59

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('dbApp', '0002_alter_r_details_unique_together'),
    ]

    operations = [
        migrations.AlterIndexTogether(
            name='r_details',
            index_together={('reciept_id', 'item_id')},
        ),
    ]
