# Generated by Django 4.1.4 on 2022-12-19 13:36

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('dbApp', '0003_delete_kero'),
    ]

    operations = [
        migrations.CreateModel(
            name='Admin',
            fields=[
                ('user_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, primary_key=True, serialize=False, to='dbApp.user')),
                ('church', models.CharField(max_length=254)),
            ],
        ),
        migrations.AlterField(
            model_name='userfavchurch',
            name='user_id',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='dbApp.donor'),
        ),
    ]
