# Generated by Django 4.1.4 on 2022-12-19 18:12

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('dbApp', '0003_alter_r_details_index_together'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='church',
            name='items',
        ),
        migrations.AddField(
            model_name='itemdetails',
            name='church_id',
            field=models.ForeignKey(default=-1, on_delete=django.db.models.deletion.CASCADE, to='dbApp.church'),
        ),
        migrations.AlterUniqueTogether(
            name='itemdetails',
            unique_together={('church_id', 'item_id')},
        ),
        migrations.AlterIndexTogether(
            name='itemdetails',
            index_together={('church_id', 'item_id')},
        ),
    ]
