# Generated by Django 4.1.4 on 2022-12-17 21:45

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('dbApp', '0003_roles_alter_card_user_id_alter_reserves_user_id_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='roles',
            name='roleid',
        ),
    ]
