# Generated by Django 4.1.4 on 2022-12-19 13:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dbApp', '0004_admin_alter_userfavchurch_user_id'),
    ]

    operations = [
        migrations.AddField(
            model_name='donor',
            name='fav_church',
            field=models.ManyToManyField(to='dbApp.church'),
        ),
    ]
