# Generated by Django 4.1.4 on 2022-12-20 18:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dbApp', '0004_remove_church_items_itemdetails_church_id_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='card',
            name='card_num',
            field=models.CharField(max_length=254, primary_key=True, serialize=False),
        ),
        migrations.AlterField(
            model_name='card',
            name='cvv',
            field=models.IntegerField(max_length=254),
        ),
    ]
