# Generated by Django 4.1.4 on 2022-12-19 23:39

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dbApp', '0004_remove_church_items_itemdetails_church_id_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='card',
            name='card_id',
            field=models.AutoField(default=-1, primary_key=True, serialize=False),
        ),
        migrations.AlterField(
            model_name='card',
            name='card_num',
            field=models.IntegerField(validators=[django.core.validators.MaxValueValidator(9999999999999999), django.core.validators.MinValueValidator(0)]),
        ),
    ]
