# Generated by Django 4.1.4 on 2022-12-20 18:44

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('dbApp', '0005_alter_card_card_num_alter_card_cvv'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Admin',
        ),
    ]
