# Generated by Django 4.1.4 on 2022-12-19 14:01

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('dbApp', '0005_donor_fav_church'),
    ]

    operations = [
        migrations.DeleteModel(
            name='UserFavChurch',
        ),
    ]
