# Generated by Django 4.1.4 on 2022-12-20 18:45

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('dbApp', '0006_delete_admin'),
    ]

    operations = [
        migrations.CreateModel(
            name='Admin',
            fields=[
                ('user_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, primary_key=True, serialize=False, to='dbApp.user')),
                ('church_id', models.ForeignKey(default=-1, on_delete=django.db.models.deletion.CASCADE, to='dbApp.church')),
            ],
        ),
    ]
