# Generated by Django 4.1.4 on 2022-12-20 18:51

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('dbApp', '0007_admin'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='reciept',
            name='items',
        ),
    ]
