# Generated by Django 4.1.4 on 2022-12-20 19:07

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('dbApp', '0008_remove_reciept_items'),
    ]

    operations = [
        migrations.AlterField(
            model_name='reciept',
            name='user_id',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='dbApp.donor'),
        ),
    ]
