# Generated by Django 4.1.4 on 2022-12-20 20:19

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('dbApp', '0009_alter_reciept_user_id'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='itemdetails',
            options={'ordering': ['-quantity']},
        ),
        migrations.CreateModel(
            name='Timeslots',
            fields=[
                ('time_id', models.AutoField(primary_key=True, serialize=False)),
                ('time', models.TimeField()),
                ('church_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='dbApp.church')),
            ],
        ),
        migrations.CreateModel(
            name='PeopleinNeed',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('chuch_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='dbApp.church')),
            ],
        ),
        migrations.AlterField(
            model_name='reserves',
            name='time',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='dbApp.timeslots'),
        ),
        migrations.CreateModel(
            name='Need',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('quntity', models.IntegerField()),
                ('due_date', models.DateField()),
                ('period', models.IntegerField()),
                ('item_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='dbApp.item')),
                ('people_in_need_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='dbApp.peopleinneed')),
            ],
            options={
                'ordering': ['due_date'],
                'unique_together': {('people_in_need_id', 'item_id')},
                'index_together': {('people_in_need_id', 'item_id')},
            },
        ),
    ]
