# Generated by Django 4.1.4 on 2022-12-20 23:40

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('dbApp', '0010_alter_itemdetails_options_timeslots_peopleinneed_and_more'),
    ]

    operations = [
        migrations.AlterIndexTogether(
            name='itemdetails',
            index_together=set(),
        ),
    ]
