# Generated by Django 4.1.4 on 2022-12-20 23:44

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('dbApp', '0011_alter_itemdetails_index_together'),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name='itemdetails',
            unique_together=set(),
        ),
    ]
