# Generated by Django 4.1.4 on 2022-12-21 00:25

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('dbApp', '0012_alter_itemdetails_unique_together'),
    ]

    operations = [
        migrations.AlterIndexTogether(
            name='need',
            index_together=set(),
        ),
        migrations.AlterUniqueTogether(
            name='itemdetails',
            unique_together={('church_id', 'item_id')},
        ),
    ]
