# Generated by Django 4.1.4 on 2022-12-21 01:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dbApp', '0013_alter_need_index_together_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='peopleinneed',
            name='name',
            field=models.CharField(default='', max_length=254),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='card',
            name='cvv',
            field=models.IntegerField(),
        ),
    ]
