# Generated by Django 4.1.4 on 2022-12-21 01:08

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('dbApp', '0014_peopleinneed_name_alter_card_cvv'),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name='need',
            unique_together=set(),
        ),
        migrations.RemoveField(
            model_name='need',
            name='people_in_need_id',
        ),
        migrations.DeleteModel(
            name='PeopleinNeed',
        ),
    ]
