# Generated by Django 4.1.4 on 2022-12-21 01:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dbApp', '0016_peopleinneed_need_people_in_need_id_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='need',
            name='due_date',
            field=models.DateField(null=True),
        ),
    ]
