# Generated by Django 4.1.4 on 2022-12-21 01:27

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('dbApp', '0018_remove_peopleinneed_chuch_id'),
    ]

    operations = [
        migrations.AddField(
            model_name='need',
            name='chuch_id',
            field=models.ForeignKey(default=-1, on_delete=django.db.models.deletion.CASCADE, to='dbApp.church'),
        ),
    ]
