# Generated by Django 4.1.4 on 2022-12-21 17:49

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('dbApp', '0019_need_chuch_id'),
    ]

    operations = [
        migrations.AlterIndexTogether(
            name='itemdetails',
            index_together={('church_id', 'item_id')},
        ),
    ]
