# Generated by Django 4.1.4 on 2022-12-21 17:51

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('dbApp', '0020_alter_itemdetails_index_together'),
    ]

    operations = [
        migrations.AlterIndexTogether(
            name='itemdetails',
            index_together=set(),
        ),
    ]
