# Generated by Django 4.1.4 on 2022-12-23 23:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dbApp', '0025_day_timeslots_reserves'),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name='timeslots',
            unique_together=None,
        ),
        migrations.RemoveField(
            model_name='timeslots',
            name='church_id',
        ),
        migrations.RemoveField(
            model_name='timeslots',
            name='day',
        ),
        migrations.AlterField(
            model_name='reserves',
            name='time',
            field=models.TimeField(),
        ),
        migrations.DeleteModel(
            name='Day',
        ),
        migrations.DeleteModel(
            name='Timeslots',
        ),
    ]
