# Generated by Django 4.1.4 on 2022-12-24 23:59

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('dbApp', '0026_alter_timeslots_unique_together_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='need',
            old_name='chuch_id',
            new_name='church_id',
        ),
        migrations.RenameField(
            model_name='need',
            old_name='quntity',
            new_name='quantity',
        ),
    ]
