# Generated by Django 4.1.4 on 2022-12-26 20:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dbApp', '0027_rename_chuch_id_need_church_id_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='peopleinneed',
            name='id',
            field=models.CharField(max_length=254, primary_key=True, serialize=False),
        ),
    ]
