# Generated by Django 4.1.4 on 2022-12-28 18:12

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('dbApp', '0029_alter_user_role'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Servant',
        ),
    ]
