# Generated by Django 4.1.4 on 2022-12-28 18:29

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('dbApp', '0030_delete_servant'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='R_Details',
            new_name='RecieptDetails',
        ),
    ]
