# Generated by Django 4.1.4 on 2022-12-28 18:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dbApp', '0031_rename_r_details_recieptdetails'),
    ]

    operations = [
        migrations.AlterField(
            model_name='peopleinneed',
            name='id',
            field=models.CharField(max_length=14, primary_key=True, serialize=False),
        ),
    ]
