# Generated by Django 4.1.4 on 2022-12-28 18:38

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('dbApp', '0032_alter_peopleinneed_id'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Reserves',
            new_name='Reservation',
        ),
    ]
