# Generated by Django 4.1.4 on 2022-12-28 18:39

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('dbApp', '0033_rename_reserves_reservation'),
    ]

    operations = [
        migrations.RenameField(
            model_name='reservation',
            old_name='reservation_num',
            new_name='reservation_id',
        ),
    ]
