# Generated by Django 4.1.4 on 2022-12-30 01:02

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('dbApp', '0034_rename_reservation_num_reservation_reservation_id'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='reservation',
            options={'ordering': ['date']},
        ),
    ]
