# Generated by Django 4.1.4 on 2022-12-30 01:11

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('dbApp', '0035_alter_reservation_options'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='reservation',
            options={'ordering': ['date', 'time']},
        ),
    ]
