# Generated by Django 4.1.4 on 2022-12-19 13:17

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('donateApp', '0001_initial'),
    ]

    operations = [
        migrations.DeleteModel(
            name='kero1',
        ),
    ]
