# Generated by Django 4.1.2 on 2022-10-30 14:23

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('donateApp', '0001_initial'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Members',
        ),
    ]
